name: arch_cli
description: A CLI tool for generating Flutter project templates quickly and efficiently.

version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  mason: ^0.1.0
  mason_logger: ^0.3.2
  path: ^1.9.1
  yaml: ^3.1.3
  mustache_template: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0